### ISSUE TITLE
Option pages should be named like the option pages in Picard

### ISSUE THREAD

**Issue by phw** [rdswift/picard-docs#2]
# Summary

If the options pages get named exactly like they are named in Picard we can easily link from Picard to the documentation.

On the current website we took care of carefully naming the anchors the same as the option pages in Picard, so we can link e.g. to https://picard.musicbrainz.org/docs/options/#cover directly.

For picard-docs this means renaming some of the options (e.g. cover instead of the current cover_art). Of course we could also change the names inside Picard, but this has the potential to break plugins (e.g. 

* This is a…
  * [ ] Error Report
  * [ ] Addition Request
  * [ ] Deletion Request
  * [x] Modification Request
  * [ ] Other

# Reason for the Change

# Description of the Change

# Additional Information

**Comment by rdswift** [comment]
I didn't realize that the options were linked to the help pages.  I've got the files split up and named to match the links on the options page, and will update the repository shortly.  Do you know if there are there any other pages linked that way that also need to be changed?

Also, in the course of all of this, I noticed that one of the options in the Metadata section is called "Non-album tracks"; however, the website defines this term as obsolete and has been replaced with "Standalone recording".  See [https://musicbrainz.org/doc/Standalone_Recording](https://musicbrainz.org/doc/Standalone_Recording).  Should this be changed in Picard to be consistent with the preferred use of "Standalone recording"?

**Comment by phw** [comment]
> I noticed that one of the options in the Metadata section is called "Non-album tracks"; however, the website defines this term as obsolete and has been replaced with "Standalone recording".

Yes, maybe it should. There are a couple of other cases where the naming differs. E.g. Picard is talking a lot about albums instead of releases.
