### ISSUE TITLE
Document the "Tags from filenames" tool

### ISSUE THREAD

**Issue by phw** [rdswift/picard-docs#31]
**Type of change requested**
This is an…
 - [ ] Error Report
 - [x] Addition Request
 - [ ] Deletion Request
 - [ ] Modification Request
 - [ ] Other

**Reason for the change**
There is currently not documentation for the "Tags from file names" tool.

**Describe the solution you'd like**
I think we should add a section "Generate tags from file names" under "Other Picard Tasks". Should include a screenshot of the tool, explanation of the functionality and some working examples.

**Additional context**
This functionality is often overlooked. It can be a bit quirky, but can be helpful in many cases. Some related forum discussions:

https://community.metabrainz.org/t/filename-to-tags-how-does-it-work/457039
https://community.metabrainz.org/t/tagging-from-filename/5105

**Comment by rdswift** [comment]
Are there any other tools that should be documented?  Should we have a separate **Tools** section with explanation pages for each of the items:

* Refresh
* Lookup CD...
* Lookup
* Scan
* Cluster
* Lookup in Browser
* Generate AcoustID Fingerprints
* Tags from File Names...
* Open My Collections in Browser

**Comment by phw** [comment]
Not sure, most ate already documented elsewhere and are not so much a standalone feature. But tags from file names definitely deserves its own page. I started the documentation for this.
