### ISSUE TITLE
Improve explanation of cover art whitelisted sites

### ISSUE THREAD

**Issue by rdswift** [rdswift/picard-docs#43]
**Type of change requested**
This is an…
 - [ ] Error Report
 - [ ] Addition Request
 - [ ] Deletion Request
 - [x] Modification Request
 - [ ] Other

**Reason for the change**
The current explanation of whitelisted cover art providers is a bit unclear.  See changes at https://github.com/metabrainz/picard/pull/1619

**Describe the solution you'd like**
Update the description of the configuration item to better explain the whitelist process and the list being used.

**Additional context**
None.

**Comment by phw** [comment]
Fully agreed. And even after the renaming, while it is better it is not quite clear what it does. Especially as this is kind of a legacy thing. The relationship on MB is deprecated and there should be hardly any release left with this relationship set.
