### ISSUE TITLE
Restructure file structure to support hosting on ReadTheDocs

### ISSUE THREAD

**Issue by rdswift** [rdswift/picard-docs#44]
**Type of change requested**
This is an…
 - [ ] Error Report
 - [ ] Addition Request
 - [ ] Deletion Request
 - [ ] Modification Request
 - [x] Other

**Reason for the change**
Use a structure to be able to take advantage of the features provided when hosting the documentation on ReadTheDocs.  Even if the documentation is not going to be hosted on ReadTheDocs, many of these changes will provide additional flexibility when serving the documentation from `gh-pages` or a dedicated server.

**Describe the solution you'd like**
1. ReadTheDocs does not seem to support `..` path references for images which are currently used to link all images from a common `images` directory.  I'm proposing that all images either reside in the same directory as the `*.rst` file in which they are used, or in an `images` subdirectory of the directory containing the `*.rst` file.

2. ReadTheDocs seems to prefer the root of the documentation source to be the project root directory.  Currently the root directory for the documentation source is the `source` directory.  This will require moving everything in the `source` directory up to the project root directory, with all current subdirectories of `source` to become subdirectories of the project root directory.

3. ReadTheDocs can be configured to publish each version from a branch named with the version number (e.g.:  `2.3.2` or `2.4`), thus allowing previous versions to be maintained independently.  This way corrections can be applied to earlier versions if required.  The current system freezes the content of a version's documentation when a new version is released.  Correcting errors is not (easily) supported, requiring changes be made directly to the `*.html` files already generated and stored in the `gh-pages` branch from which they are currently served.

**Additional context**
One issue in particular if considering moving the documentation hosting to ReadTheDocs is the path structure for the URL.  ReadTheDocs uses the structure:

```
/{language}/{version}/index.html
```

where `{language}` is the language code defaulting to `en`, and `{version}` is the version number (e.g.: `2.3.2` or `2.4`), `latest` (which is the default), or `stable` which is set to the highest numbered version.

The current system uses the structure:

```
/{version}/{language}/index.html
```

where `{language}` is the language code, and `{version}` is the version number starting with a `v` (e.g.: `v2.3.2` or `v2.4`).  The latest version information (from the `master` branch is served from the root directory, which duplicates the files in the highest version number directory.

If the path structure changes to match the ReadTheDocs standard (possibly by deciding to host the documentation on ReadTheDocs), the current links provided in the Community forum discussion and within Picard will break.  It may be possible to code redirects to the new locations through the use of a custom 404 page on ReadTheDocs,

It should be noted that when @zas originally requested the ability to link to a specific version's documentation, his suggestion was to have the version number precede the language in the URL path.  Unfortunately, this is not how it was developed because of potentially varying language support for different versions and the intent to try to automatically identify the user's preferred language(s) and serve the appropriate language version of the documentation.

**Comment by zas** [comment]
I'm fine with suggested changes. We'll need to provide redirections though, so the possibility of doing so has to be confirmed.
About `/{language}/{version}` vs `/{version}/{language}/`, my initial suggestion was without much knowledge of readthedocs, so I'm fine changing that if it fits better in ReadTheDocs context.

**Comment by rdswift** [comment]
> We'll need to provide redirections though, so the possibility of doing so has to be confirmed.

I agree completely.  To that end I've just added a custom 404 page processor that redirects RTD type requests to the current page structure if possible, or displays a bit more "user friendly" page consistent with our theme if the page cannot be found.  This can be tested by requesting urls such as:

- https://picard-docs.musicbrainz.org/en/2.3.2/glossary.html (RTD format specifying language, numeric version, and page)
- https://picard-docs.musicbrainz.org/en/latest/glossary.html (RTD format specifying language, latest version, and page)
- https://picard-docs.musicbrainz.org/en/2.3.2 (RTD format specifying language and numeric version, no page)
- https://picard-docs.musicbrainz.org/en/stable (RTD format specifying language and version, no page)
- https://picard-docs.musicbrainz.org/fr/2.3.2 (RTD format specifying unknown language and numeric version, no page)
- https://picard-docs.musicbrainz.org/unknown_page.html (unknown page)

This demonstrates that it is possible to code redirects within the limitations of the `gh-pages` deployment.  Of course, if and when the structure changes, the redirects will have to be coded to the reverse of what they are now.

**Comment by rdswift** [comment]
Also, I've opened a test project and linked it to RTD (reserving the name "picard-docs") to verify that any proposed changes will actually work using RTD as the hosting service, just in case we eventually decide to make the hosting service switch.

**Comment by phw** [comment]
I'm also fine with the suggested changes. I also test-drove RTD, and I like it. I think it could simplify the management of separate versions for us. Also we can still point a custom domain to it. But not big preference really, as long as we maintain the freedom to switch hosting if needed.

**Comment by rdswift** [comment]
The more I work with ReadTheDocs, the more I like it.  It definitely simplifies the documentation maintenance and publishing.  I've completed a manual translation of the 2.3.2 version of the docs to French (using Google Translate because I only speak English), and published the test suite as https://picard-documentation.readthedocs.org if anyone is interested in seeing how it works.

**Comment by zas** [comment]
And the French translation looks pretty good (of course, it'll need review but, as is, good enough). Good job!

**Comment by phw** [comment]
So I think to transition we could have everything setup on RTD as we need it and then just switch over the domain. If it makes maintencance of multiple versions and languages easier I'm all for it.

**Comment by rdswift** [comment]
Actually, now that I have the site restructured and the scripts in place to automate everything, I'd actually recommend keeping it hosted via gh-pages.  That allows a bit more flexibility, and the structure can easily be copied to a stand-alone server if desired.

Restructuring completed in commits:

- https://github.com/rdswift/picard-docs/commit/5d7493306aeedce5dfcdd3da1738edd5cfdd99ea
- https://github.com/rdswift/picard-docs/commit/9b77ca5ad60cdcb843f15a71e2d6dbc4fa3fc103
