### ISSUE TITLE
The scripting link from Picard results in "File Not Found"

### ISSUE THREAD

**Issue by rdswift** [rdswift/picard-docs#66]
### Type of change requested

- [x] Bug Report
- [ ] Enhancement Request
- [ ] Other

### What you would like to see changed

Currently, when a user clicks on the "**_Open scripting documentation in your browser_**" link in Picard, the browser is directed to a link that is no longer there, and thus presents the "File Not Found" page.  The `scripting.html` file should either be relocated to the proper location according to the Picard link, or there should be an automatic redirection to the proper file location to prevent the "File Not Found" display.

### Additional context

None.

**Comment by rdswift** [comment]
Fully resolved with additional commit https://github.com/rdswift/picard-docs/commit/7aa6fb4ca6a6f02fe9837e4308b679ebadf9522c.

**Comment by phw** [comment]
Thanks a lot for this

**Comment by rdswift** [comment]
Since I broke it in the first place, it's only right that I should fix it.  :wink:   Besides, it gave me an opportunity to make the redirection logic a bit more robust in the process.
