### ISSUE TITLE
Publish only major.minor version documentation (not patch versions)

### ISSUE THREAD

**Issue by rdswift** [rdswift/picard-docs#68]
### Type of change requested

- [x] Improvement Request (change an existing part of the project)
- [ ] Enhancement Request (add something new to the project)
- [x] Other

### What you would like to see changed

Only publish documentation at the `major.minor` level (e.g. `2.5` or `3.0`) and not at the `patch` (micro) level (e.g. `2.4.2`).  Redirect calls for a `patch` version to display the parent `major.minor` version instead.

### Why you would like to see this changed

Simplify maintenance by not having to maintain each `patch` version separately.  Also reduce required disk space on the server.

### Additional context

The current `major.minor` release documentation would need to be updated to the latest `patch` version for the release before removing the `patch` versions.

There are a few different ways that this could proceed:

1. Update the `major.minor` documentation to the latest associated `patch` version and remove the `patch` versions.  Redirect all calls for `patch` versions to display the parent `major.minor` version.  Only publish and retain `major.minor` versions.

2. Keep existing `patch` versions.  Only publish and retain `major.minor` versions in the future.

3. Continue the current practice of publishing and retaining all `major.minor` and `patch` versions, and discard this change request.

There has been some initial discussion about this on IRC between `outsidecontext` and `rdswift`:

-----

***\<rdswift\>*** No rush whatsoever, but when you have a chance can you please look at https://github.com/rdswift/picard-docs/wiki/Publishing-Logic and https://github.com/rdswift/picard-docs/wiki/Repository-Structure to see if they make sense and are useful?  I'm also thinking of putting together some notes regarding preferences in the RST files (like using in-line :index: entries rather than index directives because the in-line entries are added to the language translation catalogs).  Thanks.

***\<outsidecontext\>*** hi, the publishing logic looks good to me. one thing I wonder is whether we should maybe settle to only have documentation for the minor versions (2.5, 2.6) and not the patch versions. usually we don't have big changes there, but we might have multiple updates to the documentation during e.g. the 2.5 cycle

***\<outsidecontext\>*** so I would actially be in favor of a policy that we do e.g. a 2.6 doc release only, have a 2.6 doc branch then and update that if necessary.

***\<rdswift\>*** That makes really good sense to me.  Is Picard only set to request documentation at the minor level now, or will that also need to be changed?

***\<outsidecontext\>*** I would like to change this for the 2.6 release then, but stay with it for 2.5.3 (which I think we will do before christmas)

***\<rdswift\>*** Or should I code some sort of redirect at the documentation server end?

***\<outsidecontext\>*** would be another option, then we could also do it for older releases if we setup the tags and branches properly

***\<outsidecontext\>*** but good topic: how would we go about having a redirect? We had a change from scripting.html to extending/scripting.html at some point, and now the link in Picard scripting is broken :(

***\<rdswift\>*** I was mostly thinking of redirecting versions.  The different path thing is a bit tougher, but I have a way in mind.  I didn't realize that I broke it.

***\<rdswift\>*** Do you know of any other paths that I broke?

***\<outsidecontext\>*** I see, this would be all in the gh-pages branch I guess. We probably would need to place a file at the old location to do the redirect

***\<outsidecontext\>*** that's the only one I am aware of. that's the link going from the built-in scripting docs in picard to picard-docs

***\<rdswift\>*** Nope.  I would do it in the 404.html page which has some logic built in to try to find and redirect to the correct page before displaying the "not found" message.

***\<outsidecontext\>*** I will change it in Picard, but I thought it would probably be also good to have some redirection in place

***\<outsidecontext\>*** ah, even better

***\<rdswift\>*** I'll add a ticket to work on the redirect thing and should have something ready this weekend.  Thanks.

-----

**Comment by zas** [comment]
I'm fine with this, patch versions shouldn't add much features anyway.

**Comment by rdswift** [comment]
Here is another draft for your review and comment regarding [publishing a new version of the documentation](https://github.com/rdswift/picard-docs/wiki/Publishing-a-New-Version).  I really want to try to get a good understanding of how you want to see this whole documentation system working, so that I don't end up making changes that you don't want.  Thanks.

**Comment by phw** [comment]
> patch versions shouldn't add much features anyway.

Yes, that's my thinking as well. This has been the reality for basically all 2.x releases. Even when we had the docs on the old website we usually prepared an update for the 2.x version and had only light changes and corrections afterwards. With the new docs it turns out to be the same. Differences between patch versions in the docs are minimal at best, and usually are just corrections over the previous version. I think we simplify both our and our user's life with this :D

@rdswift: That new version publishing documentation looks good to me. For the displayed version I'm not sure, but maybe display the actual latest patch version.

We definitely should have a branch which we can push to for any updates to this version of the docs (as opposed to pushing e.g. in development changes to master).

**Comment by rdswift** [comment]
> We definitely should have a branch which we can push to for any updates to this version of the docs (as opposed to pushing e.g. in development changes to master).

Am I understanding that, for example, you want to be able to push changes to the current `2.5.2` branch (which is the same as the latest (default) `master` branch) but not have them appear in the `master` branch.  In other words, the `2.5.2` branch would be one or more commits ahead of the `master` branch (both of which are published)?  Or are you thinking that the changes be saved to a future branch such as `2.5.3` or `2.6` which is not yet published, and then merge them into the `master` branch (so that they are published) when the new version is released?  Both are certainly possible, and we should document how we want to gather the information for a pending release.  I'm thinking of using something like a `next_picard_release` branch rather than the proper numeric branch number because then once it is published you wouldn't need to apply minor corrections to both the `master` and numeric release branch to keep them in sync.  That was why I was suggesting not to create the numeric branch for a release until just prior to issuing the new release.  Or have I misunderstood?

**Comment by rdswift** [comment]
Completed with the application of commits:
- 42887daa6f1bcbcf37bca7ee8e50f3fe76d0de3a [`gh-pages`]
- b1ae9866a45b93419bfd08a2f2924888670b25c7 [`master`]
- abcae54ff32fabb24742de8106928f1b8f1a806d [`2.3`]
- cc77348b8793032d01358917ceb88c22d8aad6bf [`2.4`]
- 1deb2f6d0021bd8ce28acea76b6d621250a25adf [`2.5`]

Still need to finish the updates to the wiki.
