### ISSUE TITLE
Format: Side menu with odd padding for sections

### ISSUE THREAD

**Issue by phw** [rdswift/picard-docs#96]
### What you would like to see changed

The sidebar has odd padding between section headlines and sections. The headlines are tucked to the section before it and has a large padding to the section content:

![grafik](https://user-images.githubusercontent.com/29852/113823587-1d1cce80-977f-11eb-8c24-6d7995d279fe.png)

### Additional context

This probably was caused by recent Sphinx update. Only the 2.6 docs are affected, this is how it looks like in the 2.5 docs:

![grafik](https://user-images.githubusercontent.com/29852/113823736-4a697c80-977f-11eb-927c-76f26ed26835.png)

**Comment by phw** [comment]
This is strange, it looks good when building locally. I upgraded from Sphinx 3.1.1 to 3.5.3 on my local machine, but with both versions the sidebar renders fine.

**Comment by phw** [comment]
Found the issue after a fresh install:

> ERROR: sphinx-rtd-theme 0.5.2 has requirement docutils<0.17, but you'll have docutils 0.17 which is incompatible.

 3306e2e fixes this.

**Comment by phw** [comment]
This issue is tracked for docutils at https://github.com/readthedocs/sphinx_rtd_theme/issues/1115

**Comment by rdswift** [comment]
GREAT CATCH!  Thanks.
